# To get started with Dependabot version updates, youll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: npm
    # Look for `package.json` and `lock` files in the `root` directory
    directory: /
    # Raise PR limit from 5
    open-pull-requests-limit: 10
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: daily
    labels:
      - npm
      - dep
    groups:
      non-major-dev:
        labels:
          - dev
          - non-major
        update-types:
          - minor
          - patch
        dependency-type: development
      non-major-prod:
        labels:
          - prod
          - non-major
        update-types:
          - minor
          - patch
        dependency-type: production
      major-dev:
        labels:
          - major
          - dev
        update-types:
          - major
        dependency-type: development
      major-prod:
        labels:
          - major
          - prod
        update-types:
          - major
        dependency-type: production

  # Enable version updates for Docker
  - package-ecosystem: docker
    # Look for a `Dockerfile` in the `root` directory
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly
    labels:
      - docker
      - dep

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - github-actions
      - dep
