name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - develop
jobs:
  create-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: ignore,.github
          commit_message: update diagram [skip ci]
          artifact_name: diagram
  # get the diagram created by prev job!
  get-prev-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Get diagram artifacts (REST API)
        id: get_diagram_artifacts
        uses: octokit/request-action@v2.1.9
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_diagram_artifacts.outputs.data }}'"
