name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - develop
jobs:
  # get the latest diagram
  get-latest-diagram:
    runs-on: ubuntu-latest
    outputs:
      prev_artifact_url: ${{ steps.extract-artifact-data.outputs.result }}
    steps:
      - name: Get diagram artifacts (REST API)
        id: get_diagram_artifacts
        uses: octokit/request-action@v2.1.9
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get 1st artifact id
        id: extract-artifact-data
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const data = ${{ steps.get_diagram_artifacts.outputs.data }};
            const art_zip_url = data.artifacts[0].archive_download_url;
            return art_zip_url;

  create-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: ignore,.github
          commit_message: update diagram [skip ci]
          artifact_name: diagram

  # foo:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - get-latest-diagram
  #   steps:
  #     - name: bar
  #       env:
  #         ARTIFACT_URL: ${{ needs.get-latest-diagram.outputs.prev_artifact_url }}
  #       run: |
  #         echo $ARTIFACT_URL

  compare-diagrams:
    runs-on: ubuntu-latest
    needs:
      - get-latest-diagram
      - create-diagram
    steps:
      - name: Get previous diagram
        env:
          ARTIFACT_URL: ${{ fromJson(needs.get-latest-diagram.outputs.prev_artifact_url) }}
        run: |
          curl -L \
            -H "Accept: application/vnd.github+raw" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -o artifact.zip \
            $ARTIFACT_URL
          mkdir -p ./diagrams
          unzip artifact.zip -d ./diagrams
          rm artifact.zip
          mv ./diagrams/diagram.svg ./diagrams/previous.svg
      - name: Get current diagram
        uses: actions/download-artifact@v4
        with:
          name: diagram
          path: ./diagram
      - name: Prepare current
        run: |
          mv ./diagram/diagram.svg ./diagrams/current.svg
      - name: Setup compare tool - Image Magic
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            imagemagick ttf-mscorefonts-installer inkscape fontconfig
      - name: Convert SVG to PNG
        run: |
          cd diagrams
          convert previous.svg previous.png
          convert current.svg current.png
      - name: Compare diagrams
        run: |
          cd diagrams
          compare current.png previous.png diff.png
      - name: Push diff
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('./diagrams/diff.png');
            github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'diff.png',
              message: 'update diff',
              content: content.toString('base64'),
              sha: context.sha,
              branch: context.ref.replace('refs/heads/', ''),
            });
