name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - develop
jobs:
  # get the latest diagram
  get-latest-diagram:
    runs-on: ubuntu-latest
    outputs:
      prev_id: ${{ fromJson(steps.get_1st_artifact_id.outputs.result).latest_diagram_id }}
    steps:
      - name: Get diagram artifacts (REST API)
        id: get_diagram_artifacts
        uses: octokit/request-action@v2.1.9
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get 1st artifact id
        id: get_1st_artifact_id
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const data = ${{ steps.get_diagram_artifacts.outputs.data }};
            const latest_diagram_id = data.artifacts[0].id;
            console.log(`latest_diagram_id: ${latest_diagram_id}`);
            return { latest_diagram_id };

  create-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: ignore,.github
          commit_message: update diagram [skip ci]
          artifact_name: diagram

  compare-diagrams:
    runs-on: ubuntu-latest
    needs:
      - get-latest-diagram
      - create-diagram
    steps:
      - name: Get output from prev job
        run: |
          echo "direct: ${{ needs.get-latest-diagram.outputs.prev_id }}"
          echo "env: ${{ env.PREV_ID }}"
      - name: Get previous diagram
        uses: octokit/request-action@v2.1.9
        id: get_artifact
        with:
          route: GET /repos/${{ github.repository }}/actions/artifacts/${{ needs.get-latest-diagram.outputs.prev_id }}/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREV_ID: ${{ needs.get-latest-diagram.outputs.prev_id }}
      - name: Unzip previous diagram
        run: unzip -o ${{ steps.get_artifact.outputs.data }} -d diagrams/previous
      - name: Get current diagram
        uses: actions/download-artifact@v2
        with:
          name: diagram
          path: diagrams/current
      - name: Setup compare tool - Image Magic
        run: |
          sudo apt-get install -y imagemagick
      - name: Convert SVG to PNG
        run: |
          cd diagrams
          for f in **/*.svg; do
            convert "$f" "${f%.svg}.png"
          done
      - name: Compare diagrams
        run: magick compare previous/diagram.png current/diafram.png /diff.png
      - name: Push diff
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const content = fs.readFileSync('/diff.png');
            github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'diff.png',
              message: 'update diff',
              content: content.toString('base64'),
              sha: context.sha,
              branch: context.ref.replace('refs/heads/', ''),
            });
