name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - develop
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          excluded_paths: "ignore,.github"
          commit_message: "repo-viz: update diagram [skip ci]"
          artifact_name: "diagram"
          
